version: '3.4'

services:
  app: 
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - GRADLE_OPTS
        - SDK_OPTS
    environment:
      - GRADLE_OPTS
    command: npm start
    volumes:
      - .:/srv
