  
version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
            docker-compose -v
      - run:
          name: Build Images
          command: |
            docker-compose build --parallel
            docker-compose run --rm app yarn install

      - run:
          name: Tpye check App
          command: |
            docker-compose run --rm app yarn build

      - run:
          name: Build Demo App
          command: |
            docker-compose run --rm app yarn build-android


workflows:
  main:
    jobs:
      - build
